// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-jRxsCsPC1NIB7yRItXzaNAN5dSbaXoc',
    appId: '1:102410511518:web:394eebb9d965bf31e5078f',
    messagingSenderId: '102410511518',
    projectId: 'tuni-transport-20eaf',
    authDomain: 'tuni-transport-20eaf.firebaseapp.com',
    storageBucket: 'tuni-transport-20eaf.firebasestorage.app',
    measurementId: 'G-XPSTNX7HLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWSsnc82ohqjjWkygMDPB_7zbOOzLzvuc',
    appId: '1:102410511518:android:fbf375f49efdc1f8e5078f',
    messagingSenderId: '102410511518',
    projectId: 'tuni-transport-20eaf',
    storageBucket: 'tuni-transport-20eaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKzikShbZzQTjajx98aSKwkPzlvw3Ue58',
    appId: '1:102410511518:ios:46b27f52fa74440ae5078f',
    messagingSenderId: '102410511518',
    projectId: 'tuni-transport-20eaf',
    storageBucket: 'tuni-transport-20eaf.firebasestorage.app',
    androidClientId: '102410511518-qqj38a852aa632tb25ifq07h23dm5fpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKzikShbZzQTjajx98aSKwkPzlvw3Ue58',
    appId: '1:102410511518:ios:46b27f52fa74440ae5078f',
    messagingSenderId: '102410511518',
    projectId: 'tuni-transport-20eaf',
    storageBucket: 'tuni-transport-20eaf.firebasestorage.app',
    androidClientId: '102410511518-qqj38a852aa632tb25ifq07h23dm5fpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIeSkAb8fpr5EuKFjfpwz--QIcfBHxWIw',
    appId: '1:102410511518:web:7925c56b7da57c9be5078f',
    messagingSenderId: '102410511518',
    projectId: 'tuni-transport-20eaf',
    authDomain: 'tuni-transport-20eaf.firebaseapp.com',
    storageBucket: 'tuni-transport-20eaf.firebasestorage.app',
    measurementId: 'G-4GQ87YWQ8X',
  );

}